import { cn } from "@/lib/utils";
import { QueryClientProvider } from "@/providers/query-client-provider";
import { UserProvider } from "@/providers/user-provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, "antialiased bg-background")}>
        <UserProvider>
          <QueryClientProvider>
            {children}
            <Toaster />
          </QueryClientProvider>
        </UserProvider>
      </body>
    </html>
  );
}
